<?php

namespace App\Console\Commands;

use App\Models\AppNotification;
use App\Models\Task;
use App\Models\TaskActivity;
use App\Models\RecurringTask;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Console\Command;

class CheckScheduledTasks extends Command
{
    protected $signature = 'tasks:check-scheduled';
    protected $description = 'Detect scheduled tasks whose start time has arrived, change them to IN PROGRESS, and check overdue tasks.';

    public function handle()
    {
        $now = Carbon::now('UTC');

        // Generate at most one task per due schedule; row locks prevent duplicate runs.
        RecurringTask::where('is_active', true)->orderBy('id')->each(function ($schedule) use ($now) {
            DB::transaction(function () use ($schedule, $now) {
                $recurring = RecurringTask::lockForUpdate()->find($schedule->id);
                if (!$recurring || !$recurring->is_active) return;
                if (!$recurring->next_run_at) {
                    $recurring->update(['next_run_at' => $recurring->nextOccurrence($now)]);
                    return;
                }
                if ($recurring->next_run_at->isAfter($now)) return;

                $task = Task::create([
                    'title' => $recurring->title,
                    'description' => $recurring->description,
                    'created_by' => $recurring->created_by,
                    'assigned_to' => $recurring->assigned_to,
                    'team_id' => $recurring->team_id,
                    'priority' => $recurring->priority,
                    'status' => 'IN PROGRESS',
                    'started_at' => $now,
                ]);
                if ($recurring->assigned_to) $task->assignees()->sync([$recurring->assigned_to]);
                TaskActivity::create([
                    'task_id' => $task->id,
                    'user_id' => $recurring->created_by,
                    'action' => 'created',
                    'metadata' => ['note' => 'Generated by recurring workflow', 'recurring_task_id' => $recurring->id],
                ]);
                $recipients = $recurring->assigned_to ? collect([$recurring->assigned_to]) : ($recurring->team ? $recurring->team->members->pluck('id') : collect());
                foreach ($recipients as $userId) {
                    AppNotification::create([
                        'user_id' => $userId,
                        'task_id' => $task->id,
                        'title' => 'Recurring task ready',
                        'message' => 'Your recurring task is ready: ' . $task->title,
                    ]);
                }
                $recurring->update(['last_run_at' => $now, 'next_run_at' => $recurring->nextOccurrence($now)]);
                $this->info("Generated recurring task #{$task->id}");
            });
        });

        // 1. Detect scheduled tasks whose start time has arrived
        $scheduledTasks = Task::with(['assignee', 'assignees'])
            ->where('status', 'SCHEDULED')
            ->whereNotNull('scheduled_at')
            ->where('scheduled_at', '<=', $now)
            ->get();

        foreach ($scheduledTasks as $task) {
            $task->update([
                'status' => 'IN PROGRESS',
                'started_at' => $now,
            ]);

            TaskActivity::create([
                'task_id' => $task->id,
                'user_id' => $task->created_by,
                'action' => 'started',
                'metadata' => ['note' => 'Automatically started by system schedule'],
            ]);

            // Notify Assignees
            $assignees = $task->assignees->isNotEmpty() ? $task->assignees : ($task->assignee ? collect([$task->assignee]) : collect());
            foreach ($assignees as $assignee) {
                AppNotification::create([
                    'user_id' => $assignee->id,
                    'title' => '⏰ Scheduled Task Started',
                    'message' => "Your scheduled task \"{$task->title}\" is now IN PROGRESS.",
                    'task_id' => $task->id,
                ]);
            }

            $this->info("Started scheduled task #{$task->id}: {$task->title}");
        }

        // 2. Detect approaching deadlines (due in next 1 hour)
        $approachingTasks = Task::with(['assignee', 'assignees'])
            ->where('status', 'IN PROGRESS')
            ->whereNotNull('deadline')
            ->whereBetween('deadline', [$now, $now->copy()->addHour()])
            ->get();

        foreach ($approachingTasks as $task) {
            $assignees = $task->assignees->isNotEmpty() ? $task->assignees : ($task->assignee ? collect([$task->assignee]) : collect());
            foreach ($assignees as $assignee) {
                // Avoid duplicate notification if already sent
                $exists = AppNotification::where('user_id', $assignee->id)
                    ->where('task_id', $task->id)
                    ->where('title', '⚠️ Deadline Approaching')
                    ->where('created_at', '>=', $now->copy()->subHours(2))
                    ->exists();

                if (!$exists) {
                    AppNotification::create([
                        'user_id' => $assignee->id,
                        'title' => '⚠️ Deadline Approaching',
                        'message' => "Task \"{$task->title}\" is due soon at " . Carbon::parse($task->deadline)->timezone('Asia/Manila')->format('h:i A') . ' (UTC+8)',
                        'task_id' => $task->id,
                    ]);
                }
            }
        }

        // 3. Tell owners (and whoever created the task) once when a deadline has passed.
        $overdueTasks = Task::with(['assignee', 'assignees', 'team.members'])
            ->whereIn('status', ['SCHEDULED', 'IN PROGRESS'])
            ->whereNotNull('deadline')
            ->where('deadline', '<', $now)
            ->get();

        foreach ($overdueTasks as $task) {
            $owners = $task->assignees->isNotEmpty() ? $task->assignees->pluck('id') : ($task->assigned_to ? collect([$task->assigned_to]) : ($task->team ? $task->team->members->pluck('id') : collect()));
            foreach ($owners->push($task->created_by)->filter()->unique() as $userId) {
                // One alert per person per deadline: a later notification only counts if it came after the deadline passed.
                $alreadySent = AppNotification::where('user_id', $userId)
                    ->where('task_id', $task->id)
                    ->where('title', '🚨 Task Overdue')
                    ->where('created_at', '>=', $task->deadline)
                    ->exists();
                if ($alreadySent) continue;
                AppNotification::create([
                    'user_id' => $userId,
                    'task_id' => $task->id,
                    'title' => '🚨 Task Overdue',
                    'message' => "\"{$task->title}\" passed its deadline of " . Carbon::parse($task->deadline)->timezone('Asia/Manila')->format('M j, h:i A') . ' (UTC+8).',
                ]);
            }
        }

        $this->info("Scheduled tasks check completed.");
        return Command::SUCCESS;
    }
}
